title: "Public Domain Tapes"
subtitle: "Records of the Commons"
description: ""
author: "Josh Castle"
email: "josh@ameyama.com"
url: https://publicdomaintapes.com
explicit: "yes"
logo: /res/img/logo-sq.png
category: "Music"

permalink: /ep/:title
include: ["_pages"]
